const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
const LOGOUT_USER = 'LOGOUT_USER';


export { LOGIN_USER_FAIL, LOGIN_USER_SUCCESS, LOGIN_USER_REQUEST, LOGOUT_USER };