const ROBOT_REQUEST = 'ROBOT_REQUEST';
const ROBOT_SUCCESS = 'ROBOT_SUCCESS';
const ROBOT_FAIL = 'ROBOT_FAIL';
const CLEAR_ROBOT_ERRORS = 'CLEAR_ROBOT_ERRORS';
const CLEAR_ROBOT_ERROR = 'CLEAR_ROBOT_ERROR';
const CLEAR_ROBOTS = 'CLEAR_ROBOTS';
const USER_INFO = 'USER_INFO';
const SET_TIMER = 'SET_TIMER';
const CLEAR_TIMER = 'CLEAR_TIMER';

const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
const USER_INITIAL = 'USER_INITIAL';

const LOADING_MSG = 'LOADING_MSG';



export {
    ROBOT_FAIL,
    ROBOT_REQUEST,
    ROBOT_SUCCESS,
    CLEAR_ROBOT_ERRORS,
    CLEAR_ROBOTS,
    USER_INFO,
    SET_TIMER,
    CLEAR_TIMER,
    USER_INFO_REQUEST,
    USER_INFO_SUCCESS,
    USER_INITIAL,
    LOADING_MSG,
    CLEAR_ROBOT_ERROR
}